# Generated by Django 4.0.6 on 2022-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogNumber', models.CharField(max_length=50, verbose_name='Tombo')),
                ('institutionCode', models.CharField(default='UFMG', max_length=5)),
                ('language', models.CharField(default='pt', max_length=5)),
                ('family', models.CharField(blank=True, max_length=50, verbose_name='Família')),
                ('genus', models.CharField(blank=True, max_length=50, verbose_name='Gênero')),
                ('modified', models.DateField(auto_now=True)),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
    ]
