# Generated by Django 4.0.6 on 2022-07-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='specie',
            field=models.CharField(blank=True, max_length=50, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='catalogNumber',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tombo'),
        ),
    ]
